# Generated by Django 2.1.5 on 2019-01-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailupUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('e_username', models.TextField()),
                ('e_password', models.TextField()),
                ('e_client_id', models.TextField()),
                ('e_client_secret', models.TextField()),
            ],
        ),
    ]
